# MySQL 연결 정보를 정의하는 secrets.toml 파일.

[connections.mini_proj_mysql]  # 'urstory_mysql'이라는 이름의 MySQL 연결 설정.
dialect = 'mysql'            # 데이터베이스 타입을 지정 (MySQL).
username = 'miniproj'         # 데이터베이스에 접속할 사용자 이름.
password = '1234'           # 데이터베이스 접속 비밀번호.
host = 'localhost'           # 데이터베이스 호스트 (로컬 서버).
database = 'miniproject'   # 사용할 데이터베이스 이름.
